### ISSUE TITLE
Update Meeting Minutes

### ISSUE THREAD

**Issue by AbhB2303** [AbhB2303/SOEN341_Project#1]
Add the meeting minutes for the previous meetings held into the wiki on the repository.

**Comment by AbhB2303** [comment]
Meeting minutes were updated

**Comment by AbhB2303** [comment]
Updating wiki to be in repository section rather than a file in code. Assigned to @zeinebbenmami

**Comment by zeinebbenmami** [comment]
Updated on the Wiki Page
