### ISSUE TITLE
Pinning the Top Answer

### ISSUE THREAD

**Issue by matthew-williams1** [AbhB2303/SOEN341_Project#12]
As a user who frequently uses the forum to find answers to questions that have already been asked and answered, I want to be able to see the best answer as quickly as possible so that I don't waste my time looking through incorrect or incomplete answers. 
Priority # 12
Story Point Value: 4

Acceptance Test: 
1. Start the app using npm start
2. Navigate to the page on which my question is listed with all answers
3. Press the button that is present on all answers indicating that you would like to pin this answer
4. After pressing the button, the answer is highlighted and moved permanently to the top

**Comment by lailaalhalabi** [comment]
pull request #70
