### ISSUE TITLE
Extra Feature: User Profile Pages

### ISSUE THREAD

**Issue by matthew-williams1** [AbhB2303/SOEN341_Project#22]
As a user, I want to be able to go to a page that contains the questions that I have asked and the answers that I have submitted so that I can quickly access my questions to check for answers and see if my answers were accepted as the best answer.
Priority Rank: 5
Story Points: 15

Acceptance Test:

1. Start the app using npm start
2. Navigate to the User Profile page
3. Verify that all previous answers and asked questions are displayed

**Comment by lailaalhalabi** [comment]
pull request #69
