### ISSUE TITLE
New Page Creation for Answering Questions

### ISSUE THREAD

**Issue by matthew-williams1** [AbhB2303/SOEN341_Project#24]
Subtask of Issue #13 
Create a new page for all the UX elements required for answering questions on the forum
Priority Very High
Story Points: 1

Acceptance Test: 
1. Start the app using npm start
2. Navigate to the page that lists a question and all its answers
3. Verify that the button to submit an answer to the question exists

**Comment by lailaalhalabi** [comment]
pull request #24
