### ISSUE TITLE
Send user to Answering Questions page when Submit button on Asking questions page is pressed

### ISSUE THREAD

**Issue by matthew-williams1** [AbhB2303/SOEN341_Project#33]
Subtask of issue #6 and issue #27
When the submit button is pressed, send the user to the Answer questions page.
Priority: Very High
Story Points: 1

Acceptance Test: 
1. Start the app using npm start
2. Navigate to the asking questions page
3. enter text and press submit button
4. Verify that you have been brought to the answer questions page

**Comment by lailaalhalabi** [comment]
pull request #61
