### ISSUE TITLE
Accepting the Best Answer 

### ISSUE THREAD

**Issue by simrenmatharoo** [AbhB2303/SOEN341_Project#4]
The best answer will be selected by a points-based system and will be displayed at the top. 
Priority # 7
Story Point Value: 4

Acceptance Test: 
1. Start the app using npm start
2. Navigate to the page with the question that was asked and the list of answers
3. Select the button on the answer to indicate that this is the best answer

**Comment by lailaalhalabi** [comment]
As a user, I want the best answer to be displayed first so I can find the answer easily.

**Comment by lailaalhalabi** [comment]
pull request #70
