### ISSUE TITLE
Create Display Boxes for Previous Questions and Answers

### ISSUE THREAD

**Issue by matthew-williams1** [AbhB2303/SOEN341_Project#57]
Sub task of user story #22 
Create a display box that will hold the questions and answers submitted by the user.
Priority within this Epic: 2
Story Points: 2

Acceptance Test:

1. Start the app using npm start
2. Navigate to the user profile page
3. Verify that the display boxes exist

**Comment by lailaalhalabi** [comment]
pull request #61
