### ISSUE TITLE
Implement the backend connectivity of the display boxes for the User Profile page

### ISSUE THREAD

**Issue by matthew-williams1** [AbhB2303/SOEN341_Project#58]
Sub task of user story #22 
Connect the display boxes so that they can get and display the users' questions and answers from the database when the profile page is opened.
Priority within this Epic: 3
Story Points: 8

Acceptance Test:

1. Start the app using npm start
2. Navigate to the user profile page
3. Verify that the display boxes are displaying the questions and answers submitted by the user

**Comment by lailaalhalabi** [comment]
issue #69

**Comment by lailaalhalabi** [comment]
pull request #69
